# Generated by Django 4.2.7 on 2023-11-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_facilitator_approved",
            field=models.BooleanField(default=False),
        ),
    ]
