# Generated by Django 4.2.7 on 2023-11-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("get_together", "0002_alter_gettogether_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gettogether",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("face_to_face", "Face to Face"),
                    ("hybrid_event", "Hybrid Event"),
                    ("virtual_event", "Virtual Event"),
                ],
                default="face_to_face",
                max_length=50,
                null=True,
            ),
        ),
    ]
