# Generated by Django 4.2.7 on 2023-11-24 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("get_together", "0004_alter_gettogether_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
