# Generated by Django 4.2.7 on 2023-11-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_contact_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="interests",
            field=models.CharField(max_length=100),
        ),
    ]
