# Generated by Django 4.2.7 on 2023-11-25 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_contact_interests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="fullname",
            new_name="full_name",
        ),
    ]
